# Generated by Django 5.2.1 on 2025-05-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
