# Generated by Django 5.2.1 on 2025-06-02 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recipient',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='полученные_транзакции', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sender',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='отправленные_транзакции', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
