# Generated by Django 5.2.1 on 2025-06-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_recipient_customuser_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
