# Generated by Django 5.2.1 on 2025-06-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='transaction_date',
        ),
    ]
